version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 3-bullseye
        # Optional Node.js version to install
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      SECRET_KEY: SECRET_KEY
    ports:
      - 8000:8000
  front:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: 3-bullseye
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/recoco/frontend 
    command: bash -c "yarn install && yarn dev"
    ports:
      - 3000:3000
  db:
    image: postgres:13.5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  postgres-data:
